# Generated by Django 5.0.3 on 2026-02-21 04:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ZoomMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_type', models.CharField(choices=[('regular', 'Regular Class'), ('assessment', 'Assessment'), ('makeup', 'Makeup Class'), ('demo', 'Demo Class')], default='regular', max_length=15)),
                ('title', models.CharField(max_length=200)),
                ('zoom_meeting_id', models.CharField(blank=True, max_length=100)),
                ('zoom_link', models.URLField()),
                ('zoom_password', models.CharField(blank=True, max_length=50)),
                ('scheduled_at', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('is_recurring', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zoom_meetings', to='courses.enrollment')),
                ('student', models.ForeignKey(blank=True, limit_choices_to={'role': 'student'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zoom_meetings_as_student', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(limit_choices_to={'role__in': ('teacher', 'admin')}, on_delete=django.db.models.deletion.CASCADE, related_name='created_zoom_meetings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Zoom Meeting',
                'verbose_name_plural': 'Zoom Meetings',
                'db_table': 'zoom_meetings',
                'ordering': ['-scheduled_at'],
            },
        ),
    ]
